name: CI

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install uv --disable-pip-version-check
          uv tool run pdm export --pyproject | uv pip install -r - --system
      - name: Ruff format check
        run: |
          ruff format --diff
      - name: Ruff lint check
        run: |
          ruff check --output-format=github
      - name: Pyright type check
        run: |
          npx pyright
  publish:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Build package
        run: |
          pip install pdm --disable-pip-version-check
          pdm build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          print-hash: true
          verbose: true
