name: ruff checks

on: ["push", "pull_request"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM with Python 3.11
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pdm install
      - name: Ruff format check
        run: |
          pdm fmt --diff
      - name: Ruff lint check
        run: |
          pdm lint --output-format=github
