name: ruff checks

on: ["push", "pull_request"]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install uv --disable-pip-version-check
          uv tool run pdm export --pyproject | uv pip install -r - --system
      - name: Ruff format check
        run: |
          ruff format --diff
      - name: Ruff lint check
        run: |
          ruff check --output-format=github
